# Generated by Django 5.2 on 2025-04-23 17:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PetPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("lost", "Lost"), ("found", "Found")], max_length=5
                    ),
                ),
                ("pet_name", models.CharField(blank=True, max_length=100)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("size", models.CharField(blank=True, max_length=20)),
                ("last_seen_location", models.CharField(max_length=200)),
                ("last_seen_date", models.DateField()),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^\\+?\\d{10,15}$",
                            ),
                        ],
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="pet_photos/"),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet Post",
                "verbose_name_plural": "Pet Posts",
                "ordering": ["-created_date"],
            },
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
